import '../../shared/models/user_model.dart';
import '../../shared/models/test_result_model.dart';
import '../../shared/models/leaderboard_model.dart';

class MockData {
  // Mock Users
  static final List<UserModel> mockUsers = [
    UserModel(
      id: '1',
      name: 'Arjun Singh',
      email: 'arjun.singh@email.com',
      phoneNumber: '+91 98765 43210',
      age: 24,
      gender: 'Male',
      league: 'Youth',
      memberSince: DateTime.now().subtract(const Duration(days: 30)),
      profileImageUrl: 'https://i.pravatar.cc/150?img=1',
      aadhaarNumber: '1234-5678-9012',
      isVerified: true,
    ),
    UserModel(
      id: '2',
      name: 'Priya Sharma',
      email: 'priya.sharma@email.com',
      phoneNumber: '+91 98765 43211',
      age: 19,
      gender: 'Female',
      league: 'Youth',
      memberSince: DateTime.now().subtract(const Duration(days: 15)),
      profileImageUrl: 'https://i.pravatar.cc/150?img=2',
      aadhaarNumber: '1234-5678-9013',
      isVerified: true,
    ),
    UserModel(
      id: '3',
      name: 'Raj Patel',
      email: 'raj.patel@email.com',
      phoneNumber: '+91 98765 43212',
      age: 19,
      gender: 'Male',
      league: 'Youth',
      memberSince: DateTime.now().subtract(const Duration(days: 45)),
      profileImageUrl: 'https://i.pravatar.cc/150?img=3',
      aadhaarNumber: '1234-5678-9014',
      isVerified: true,
    ),
  ];

  // Mock Test Results
  static final List<TestResultModel> mockTestResults = [
    TestResultModel(
      testId: 'height_1',
      testName: 'Height Measurement',
      testType: TestType.height,
      score: 175,
      percentile: 85.5,
      completedAt: DateTime.now().subtract(const Duration(days: 2)),
      status: TestStatus.completed,
      details: {'height': 175, 'unit': 'cm'},
      duration: const Duration(minutes: 2),
    ),
    TestResultModel(
      testId: 'weight_1',
      testName: 'Weight Measurement',
      testType: TestType.weight,
      score: 70,
      percentile: 72.3,
      completedAt: DateTime.now().subtract(const Duration(days: 2)),
      status: TestStatus.completed,
      details: {'weight': 70, 'unit': 'kg'},
      duration: const Duration(minutes: 1),
    ),
    TestResultModel(
      testId: 'pushups_1',
      testName: 'Push-ups Test',
      testType: TestType.pushUps,
      score: 45,
      percentile: 90.2,
      completedAt: DateTime.now().subtract(const Duration(days: 1)),
      status: TestStatus.completed,
      details: {'count': 45, 'duration': '60s'},
      duration: const Duration(minutes: 2),
    ),
    TestResultModel(
      testId: 'situps_1',
      testName: 'Sit-ups Test',
      testType: TestType.sitUps,
      score: 0,
      percentile: 0,
      completedAt: DateTime.now(),
      status: TestStatus.notStarted,
      details: {},
    ),
    TestResultModel(
      testId: 'running_1',
      testName: 'Running Test',
      testType: TestType.running,
      score: 0,
      percentile: 0,
      completedAt: DateTime.now(),
      status: TestStatus.notStarted,
      details: {},
    ),
    TestResultModel(
      testId: 'flexibility_1',
      testName: 'Flexibility Test',
      testType: TestType.flexibility,
      score: 0,
      percentile: 0,
      completedAt: DateTime.now(),
      status: TestStatus.notStarted,
      details: {},
    ),
  ];

  // Mock Leaderboard Entries
  static final List<LeaderboardEntry> mockLeaderboardEntries = [
    LeaderboardEntry(
      rank: 1,
      userId: '1',
      userName: 'Arjun Singh',
      profileImageUrl: 'https://i.pravatar.cc/150?img=1',
      totalScore: 290,
      league: 'Youth',
      age: 24,
      gender: 'Male',
      lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
      testScores: {
        'height': 175,
        'weight': 70,
        'pushUps': 45,
        'sitUps': 38,
        'running': 42,
        'flexibility': 35,
      },
    ),
    LeaderboardEntry(
      rank: 2,
      userId: '2',
      userName: 'Priya Sharma',
      profileImageUrl: 'https://i.pravatar.cc/150?img=2',
      totalScore: 278,
      league: 'Youth',
      age: 19,
      gender: 'Female',
      lastUpdated: DateTime.now().subtract(const Duration(hours: 4)),
      testScores: {
        'height': 165,
        'weight': 58,
        'pushUps': 35,
        'sitUps': 42,
        'running': 38,
        'flexibility': 42,
      },
    ),
    LeaderboardEntry(
      rank: 3,
      userId: '3',
      userName: 'Raj Patel',
      profileImageUrl: 'https://i.pravatar.cc/150?img=3',
      totalScore: 265,
      league: 'Junior',
      age: 16,
      gender: 'Male',
      lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
      testScores: {
        'height': 170,
        'weight': 65,
        'pushUps': 40,
        'sitUps': 35,
        'running': 40,
        'flexibility': 30,
      },
    ),
    LeaderboardEntry(
      rank: 4,
      userId: '4',
      userName: 'Sneha Reddy',
      profileImageUrl: 'https://i.pravatar.cc/150?img=4',
      totalScore: 258,
      league: 'Youth',
      age: 22,
      gender: 'Female',
      lastUpdated: DateTime.now().subtract(const Duration(hours: 8)),
      testScores: {
        'height': 162,
        'weight': 55,
        'pushUps': 32,
        'sitUps': 40,
        'running': 35,
        'flexibility': 38,
      },
    ),
    LeaderboardEntry(
      rank: 5,
      userId: '5',
      userName: 'Vikram Kumar',
      profileImageUrl: 'https://i.pravatar.cc/150?img=5',
      totalScore: 245,
      league: 'Senior',
      age: 28,
      gender: 'Male',
      lastUpdated: DateTime.now().subtract(const Duration(hours: 10)),
      testScores: {
        'height': 180,
        'weight': 75,
        'pushUps': 38,
        'sitUps': 32,
        'running': 38,
        'flexibility': 28,
      },
    ),
  ];

  // Mock Test Definitions
  static final List<Map<String, dynamic>> mockTestDefinitions = [
    {
      'id': 'height',
      'name': 'Height Measurement',
      'description': 'Measure your height using camera technology',
      'icon': '📏',
      'instructions': [
        'Stand straight against a wall',
        'Position camera at eye level',
        'Ensure good lighting',
        'Follow on-screen guidance',
      ],
      'duration': '2 minutes',
      'difficulty': 'Easy',
    },
    {
      'id': 'weight',
      'name': 'Weight Measurement',
      'description': 'Enter your current weight',
      'icon': '⚖️',
      'instructions': [
        'Use a digital scale if possible',
        'Weigh yourself without shoes',
        'Enter accurate weight',
        'Include decimal places',
      ],
      'duration': '1 minute',
      'difficulty': 'Easy',
    },
    {
      'id': 'pushups',
      'name': 'Push-ups Test',
      'description': 'Complete as many push-ups as possible in 60 seconds',
      'icon': '💪',
      'instructions': [
        'Start in plank position',
        'Lower chest to ground',
        'Push back up completely',
        'Maintain proper form',
      ],
      'duration': '2 minutes',
      'difficulty': 'Medium',
    },
    {
      'id': 'situps',
      'name': 'Sit-ups Test',
      'description': 'Complete as many sit-ups as possible in 60 seconds',
      'icon': '🏃',
      'instructions': [
        'Lie on back with knees bent',
        'Place hands behind head',
        'Lift shoulders off ground',
        'Return to starting position',
      ],
      'duration': '2 minutes',
      'difficulty': 'Medium',
    },
    {
      'id': 'running',
      'name': 'Running Test',
      'description': 'Run as far as possible in 12 minutes',
      'icon': '🏃‍♂️',
      'instructions': [
        'Warm up before starting',
        'Run at steady pace',
        'Mark distance covered',
        'Record final distance',
      ],
      'duration': '15 minutes',
      'difficulty': 'Hard',
    },
    {
      'id': 'flexibility',
      'name': 'Flexibility Test',
      'description': 'Measure your flexibility using the sit-and-reach test',
      'icon': '🤸',
      'instructions': [
        'Sit with legs extended',
        'Reach forward slowly',
        'Hold position for 2 seconds',
        'Measure distance reached',
      ],
      'duration': '3 minutes',
      'difficulty': 'Easy',
    },
  ];

  // Mock Achievements
  static final List<Map<String, dynamic>> mockAchievements = [
    {
      'id': 'first_test',
      'title': 'First Steps',
      'description': 'Complete your first fitness test',
      'icon': '🎯',
      'unlocked': true,
      'unlockedAt': DateTime.now().subtract(const Duration(days: 2)),
    },
    {
      'id': 'height_master',
      'title': 'Height Master',
      'description': 'Achieve 90th percentile in height test',
      'icon': '📏',
      'unlocked': false,
      'unlockedAt': null,
    },
    {
      'id': 'pushup_warrior',
      'title': 'Push-up Warrior',
      'description': 'Complete 40+ push-ups in 60 seconds',
      'icon': '💪',
      'unlocked': true,
      'unlockedAt': DateTime.now().subtract(const Duration(days: 1)),
    },
    {
      'id': 'consistency',
      'title': 'Consistency Champion',
      'description': 'Complete tests for 7 consecutive days',
      'icon': '🔥',
      'unlocked': false,
      'unlockedAt': null,
    },
  ];

  // Mock Videos
  static final List<Map<String, dynamic>> mockVideos = [
    {
      'id': '1',
      'title': 'Proper Push-up Technique',
      'description': 'Learn the correct form for push-ups',
      'thumbnailUrl': 'https://picsum.photos/300/200?random=1',
      'duration': '5:30',
      'category': 'Tutorial',
      'uploadedAt': DateTime.now().subtract(const Duration(days: 7)),
    },
    {
      'id': '2',
      'title': 'Flexibility Exercises',
      'description': 'Improve your flexibility with these exercises',
      'thumbnailUrl': 'https://picsum.photos/300/200?random=2',
      'duration': '8:15',
      'category': 'Exercise',
      'uploadedAt': DateTime.now().subtract(const Duration(days: 5)),
    },
    {
      'id': '3',
      'title': 'Running Form Tips',
      'description': 'Optimize your running technique',
      'thumbnailUrl': 'https://picsum.photos/300/200?random=3',
      'duration': '6:45',
      'category': 'Tutorial',
      'uploadedAt': DateTime.now().subtract(const Duration(days: 3)),
    },
  ];
}
